### ISSUE TITLE
A question about CWQ test dataset

### ISSUE THREAD

**Issue by menglor** [RichardHGL/WSDM2021_NSM#10]
Does the **ComplexWebQuestions_test_wans.json**  file that appears in the code contain the answer to the question? How do I find this file?

**Comment by RichardHGL** [comment]
You can find it from https://github.com/lanyunshi/KBQA-GST. But I'd suggest evaluate through leaderboard. There may be some difference between local evaluation and leaderboard.

**Comment by menglor** [comment]
thanks.

**Comment by menglor** [comment]
One more question, how much RAM and GPU memory do you need to train cwq dataset at least?

**Comment by RichardHGL** [comment]
I guess it also fit into 12GB GPU, 64 GB RAM. You can try to reduce batch size to fit your machine.

**Comment by menglor** [comment]
Thank you for the reply.
