### ISSUE TITLE
nsm-final.ckpt文件请求

### ISSUE THREAD

**Issue by Just-For-Fun77** [RichardHGL/WSDM2021_NSM#15]
您好，可以发我一份/checkpoint/pretrain中的nsm-final.ckpt文件吗，我想优化teacher部分，已公布的ckpt_report文件中仅有teacher和student的，如果可以的话万分感谢，邮箱地址是q1533664997@163.com

**Comment by RichardHGL** [comment]
建议自己按照我给出的命令运行nsm模型，最后一轮存下来的结果即为nsm-final.ckpt

**Comment by Just-For-Fun77** [comment]
跑了10次左右，结果与paper中的结论始终差1%左右，希望您能发我一份最优结果的ckpt，谢谢谢谢

**Comment by RichardHGL** [comment]
建议直接使用你跑出来的ckpt，调一下学习率和decay之类的，我之前的版本有点不好找了

**Comment by Just-For-Fun77** [comment]
哦哦好的知道了谢谢谢谢
