### ISSUE TITLE
你好，我用webqsp数据集跑出的结果如图，为什么给出的Hit值和F值都用平均值表示呢，能不能看到单独的模型结果呢

### ISSUE THREAD

**Issue by zhangmingdao** [RichardHGL/WSDM2021_NSM#17]
![K%Z1KOAY$}1ECFY2(`DV~JY](https://user-images.githubusercontent.com/92926709/154907787-e0dff4d5-4e75-4e0a-ae39-94889e559094.png)

**Comment by RichardHGL** [comment]
The avg_hits represent the model result, precision, recall, f1 are related to the hyper-parameter eps
