### ISSUE TITLE
KB id to entity names mapping

### ISSUE THREAD

**Issue by cmavro** [RichardHGL/WSDM2021_NSM#21]
Hi very interesting work!

I noticed in CWQ/entities.txt and webqsp/entities.txt only KG Ids are included.
Is the mapping from these ids to their textual names somewhere stored? Or should I run the preprocessing steps myself to obtain them?

Thanks,
Costas

**Comment by RichardHGL** [comment]
You can obtain entity name with /type/object/name relation. Fetch all triples of this relation from Freebase Dump
