### ISSUE TITLE
Whether the intermediate entities of the reasoning path can be obtained in the code

### ISSUE THREAD

**Issue by 1700022825** [RichardHGL/WSDM2021_NSM#23]
Hello, can I get the intermediate entities of the reasoning path mentioned in the paper? If so, which file can I find it in?
Looking forward to hearing from you

**Comment by RichardHGL** [comment]
We don't save the intermediate entities. If you want to generate them, you can train a model and then save the intermediate entities according to the intermediate probability distribution

**Comment by 1700022825** [comment]
OK, thank you for your reply.
