### ISSUE TITLE
How to work with  private KG

### ISSUE THREAD

**Issue by DecemberM** [RichardHGL/WSDM2021_NSM#28]
could this program work on private KG，If so, what should be done
hoping to your reply

**Comment by RichardHGL** [comment]
I would suggest following the preprocessing to handle a new dataset with private KG. https://github.com/RichardHGL/WSDM2021_NSM/tree/main/preprocessing/Freebase

**Comment by papayaa66** [comment]
> could this program work on private KG，If so, what should be done hoping to your reply

Hi DecemberM, I hope you're doing well! I wanted to follow up on your previous question. Have you managed to implement the feature? Also, I was wondering if the dataset is stored in a Neo4j database. I would appreciate your feedback!
