### ISSUE TITLE
hello!  how can I find CWQ dataset?

### ISSUE THREAD

**Issue by MingdongC** [RichardHGL/WSDM2021_NSM#9]

**Comment by RichardHGL** [comment]
original dataset  at https://www.tau-nlp.org/compwebq. The preprocessed version can be found at https://drive.google.com/drive/folders/1qRXeuoL-ArQY7pJFnMpNnBu0G-cOz6xv?usp=sharing. You can know more details about it  referring to the Training instruction in the Readme.md
